# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: knage <knage@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/05/22 14:54:56 by knage             #+#    #+#              #
#    Updated: 2017/05/22 14:55:02 by knage            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = awesomephonebook

SRC = main.cpp

FLAGS = -Wall -Wextra -Werror

all:
	@clang++ $(FLAGS) $(SRC) -o $(NAME)

clean:
	@rm -f $(NAME)
