NAME = ft_retro

SRC = main.cpp Game.class.cpp Player.class.cpp Draw.class.cpp Bullet.class.cpp BulletEvent.class.cpp

FLAGS = -Wall -Wextra -Werror

all:
	@clang++ $(FLAGS) $(SRC) -lncurses -o $(NAME)
